# Site

title: Leaflet in R
handouts:
  - worksheet-1.R
  - worksheet-2.R
  - worksheet-3.R
  - worksheet-4.R
  - data/nlcd_crop.grd
  - data/nlcd_crop.gri
  - data/wqp_sites
  - data/cb_2016_us_county_5m
  - data/huc250k
  - data/README.md
tag: v0.1
lesson: 8
instructor: Kelly Hondula
authors: 
- Kelly Hondula
- Ian Carroll

# Slides

slide_sorter:
  - intro
  - leaflet
  - layers
  - datalayers
  - leafletshiny
  - leafletproxy
  - conclude

#####################################
# Only modify content above or risk #
# merge conflicts with upstream.    #
#####################################

# Style

styleurl: https://cdn.rawgit.com/sesync-ci/lesson-style/v1.3/docs
reveal: https://cdn.rawgit.com/hakimel/reveal.js/3.5.0

# Jekyll

markdown: kramdown
collections:
  - slides
